### ISSUE TITLE
Animated web files are not supported

### ISSUE THREAD

**Issue by KalhariL** [sejda-pdf/webp-imageio#15]
Following exception occurs when an animated web file is read

Caused by: java.io.IOException: Decode returned code VP8_STATUS_BITSTREAM_ERROR
	at com.luciad.imageio.webp.WebP.decode(WebP.java:65) ~[webp-imageio-0.1.6.jar:?]
	at com.luciad.imageio.webp.WebPReader.read(WebPReader.java:158) ~[webp-imageio-0.1.6.jar:?]

**Comment by heinrichWeichert** [comment]
I encountered this error:  Decode returned code VP8_STATUS_UNSUPPORTED_FEATURE
