### ISSUE TITLE
 java.lang.NoClassDefFoundError: javax/imageio/ImageTypeSpecifier

### ISSUE THREAD

**Issue by costerutilo** [sejda-pdf/webp-imageio#17]
Got an error on 

openjdk version "11.0.11" 2021-04-20 
Unbuntu 20.04

When 

ImageIO.write(myBufferedImage, "webp", myNewFile)

Caused by: java.lang.NoClassDefFoundError: javax/imageio/ImageTypeSpecifier
        **at com.luciad.imageio.webp.WebPImageWriterSpi.canEncodeImage(WebPImageWriterSpi.java:62)**
        at java.desktop/javax.imageio.ImageIO$CanEncodeImageAndFormatFilter.filter(ImageIO.java:600)
        at java.desktop/javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:876)
        at java.desktop/javax.imageio.spi.FilterIterator.<init>(ServiceRegistry.java:870)
        at java.desktop/javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:518)
        at java.desktop/javax.imageio.ImageIO.getImageWriters(ImageIO.java:1172)
        at java.desktop/javax.imageio.ImageIO.getWriter(ImageIO.java:1609)
        at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1540)
        at eu.utilo.SuperController.saveImg(SuperController.groovy:167)
        at eu.utilo.onlineAtelier.myArtPage.MyArtPageSuperController.saveUploadedImage(MyArtPageSuperController.groovy:69)
        at eu.utilo.onlineAtelier.myArtPage.MyEventsController.$tt__doChangeEventPic(MyEventsController.groovy:141)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at grails.gorm.transactions.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
        at grails.gorm.transactions.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        ... 37 common frames omitted

**Comment by zkj881225** [comment]
i have same question.

**Comment by daMeng1024** [comment]
so am i. but different env

**Comment by Mararsh** [comment]
```
        IIORegistry registry = IIORegistry.getDefaultInstance();

        registry.registerServiceProvider(new WebPImageWriterSpi());
        registry.registerServiceProvider(new WebPImageReaderSpi());
```
